### ISSUE TITLE
regarding the requirements.txt 

### ISSUE THREAD

**Issue by Connection-Point** [AshishGusain17/Vehicle-Warning-Indicator-System#2]
May i know that what are the library that are going to install for this project to work correctly? cuz I'm having difficulty to launch the program correctly.

**Comment by AshishGusain17** [comment]
Hi, major dependencies are Python 3.0, TensorFlow 2.0, openCV.
Apart from these, Python libraries like imutils, scikit-learn will also be required...You can check that while running the code and as per the error, you can install those pip libraries.
I would recommend you to install conda to maintain environment and not install these libraries globally.
